print("\n")
print("****************************************************")
print("|-------------------- HANDPONG --------------------|")
print("|                                                  |")
print("|  By RICARDO ILLA                                 |")
print("|                                                  |")
print("|  Email : ricardo.illa2@gmail.com                 |")
print("|                                                  |")    
print("****************************************************")